/*
VMware Fusion REST API

Testing VMPowerManagementAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package vmrest

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	vmrest "github.com/kodal/vmrest-go-client"
)

func Test_vmrest_VMPowerManagementAPIService(t *testing.T) {

	configuration := vmrest.NewConfiguration()
	apiClient := vmrest.NewAPIClient(configuration)

	t.Run("Test VMPowerManagementAPIService ChangePowerState", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var id string

		resp, httpRes, err := apiClient.VMPowerManagementAPI.ChangePowerState(context.Background(), id).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test VMPowerManagementAPIService GetPowerState", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var id string

		resp, httpRes, err := apiClient.VMPowerManagementAPI.GetPowerState(context.Background(), id).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
