/*
 * VMware Fusion REST API
 *
 * vmrest 1.3.1 build-24585314
 *
 * API version: 1.3.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// DNS configuration
type DnsConfig struct {
	Hostname string `json:"hostname,omitempty"`
	Domainname string `json:"domainname,omitempty"`
	Server []string `json:"server,omitempty"`
	Search []string `json:"search,omitempty"`
}
