/*
 * VMware Fusion REST API
 *
 * vmrest 1.3.1 build-24585314
 *
 * API version: 1.3.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package vmrest

type VmGuestIsolation struct {
	CopyDisabled string `json:"copyDisabled,omitempty"`
	DndDisabled string `json:"dndDisabled,omitempty"`
	HgfsDisabled string `json:"hgfsDisabled,omitempty"`
	PasteDisabled string `json:"pasteDisabled,omitempty"`
}
