/*
 * VMware Fusion REST API
 *
 * vmrest 1.3.1 build-24585314
 *
 * API version: 1.3.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package vmrest

// The port forwarding
type Portforward struct {
	Port int32 `json:"port"`
	Protocol string `json:"protocol"`
	Desc string `json:"desc"`
	Guest *PortforwardGuest `json:"guest"`
}
