/*
 * VMware Fusion REST API
 *
 * vmrest 1.3.1 build-24585314
 *
 * API version: 1.3.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package vmrest

type VmRrgistrationInformation struct {
	// Registered VM name id
	Id string `json:"id,omitempty"`
	// Registered VM path
	Path string `json:"path,omitempty"`
}
