/*
 * VMware Fusion REST API
 *
 * vmrest 1.3.1 build-24585314
 *
 * API version: 1.3.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// The MAC to IP setting
type MactoIp struct {
	Vmnet string `json:"vmnet"`
	Mac string `json:"mac"`
	Ip string `json:"ip"`
}
