/*
 * VMware Fusion REST API
 *
 * vmrest 1.3.1 build-24585314
 *
 * API version: 1.3.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package vmrest

type VmRemoteVnc struct {
	VNCEnabled string `json:"VNCEnabled,omitempty"`
	VNCPort int32 `json:"VNCPort,omitempty"`
}
