/*
 * VMware Fusion REST API
 *
 * vmrest 1.3.1 build-24585314
 *
 * API version: 1.3.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package vmrest

// Information about a NIC
type NicIpStack struct {
	Mac string `json:"mac"`
	// IP address(es) of the interface (CIDR)
	Ip []string `json:"ip,omitempty"`
	Dns *DnsConfig `json:"dns,omitempty"`
	Wins *WinsConfig `json:"wins,omitempty"`
	Dhcp4 *DhcpConfig `json:"dhcp4,omitempty"`
	Dhcp6 *DhcpConfig `json:"dhcp6,omitempty"`
}
