/*
 * VMware Fusion REST API
 *
 * vmrest 1.3.1 build-24585314
 *
 * API version: 1.3.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type DaemonState string

// List of DaemonState
const (
	ON_DaemonState DaemonState = "on"
	OFF_DaemonState DaemonState = "off"
)
