/*
 * VMware Fusion REST API
 *
 * vmrest 1.3.1 build-24585314
 *
 * API version: 1.3.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type VmPowerOperation string

// List of VMPowerOperation
const (
	ON_VmPowerOperation VmPowerOperation = "on"
	OFF_VmPowerOperation VmPowerOperation = "off"
	SHUTDOWN_VmPowerOperation VmPowerOperation = "shutdown"
	SUSPEND_VmPowerOperation VmPowerOperation = "suspend"
	PAUSE_VmPowerOperation VmPowerOperation = "pause"
	UNPAUSE_VmPowerOperation VmPowerOperation = "unpause"
)
