/*
 * VMware Fusion REST API
 *
 * vmrest 1.3.1 build-24585314
 *
 * API version: 1.3.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type PortforwardParameter struct {
	GuestIp string `json:"guestIp"`
	GuestPort int32 `json:"guestPort"`
	Desc string `json:"desc,omitempty"`
}
