/*
 * VMware Fusion REST API
 *
 * vmrest 1.3.1 build-24585314
 *
 * API version: 1.3.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package vmrest

// The virtual network
type Network struct {
	// Name of virtual network
	Name string `json:"name"`
	Type_ string `json:"type"`
	Dhcp string `json:"dhcp"`
	Subnet string `json:"subnet"`
	Mask string `json:"mask"`
}
