/*
 * VMware Fusion REST API
 *
 * vmrest 1.3.1 build-24585314
 *
 * API version: 1.3.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package vmrest

// Routing entry
type RouteEntry struct {
	Dest string `json:"dest"`
	Prefix int32 `json:"prefix"`
	Nexthop string `json:"nexthop,omitempty"`
	Interface_ int32 `json:"interface"`
	Type_ int32 `json:"type"`
	Metric int32 `json:"metric"`
}
