/*
 * VMware Fusion REST API
 *
 * vmrest 1.3.1 build-24585314
 *
 * API version: 1.3.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package vmrest

type NicDeviceParameter struct {
	// The network type of network adapter
	Type_ string `json:"type"`
	// The vmnet name, it should only be used while type is custom
	Vmnet string `json:"vmnet"`
}
