/*
 * VMware Fusion REST API
 *
 * vmrest 1.3.1 build-24585314
 *
 * API version: 1.3.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package vmrest

// The list of network adapters
type NicDevices struct {
	Num int32 `json:"num"`
	// The network adapter added to this VM
	Nics []NicDevice `json:"nics"`
}
