/*
 * VMware Fusion REST API
 *
 * vmrest 1.3.1 build-24585314
 *
 * API version: 1.3.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type NicDevice struct {
	Index int32 `json:"index"`
	// The network type of network adapter
	Type_ string `json:"type"`
	// The vmnet name
	Vmnet string `json:"vmnet"`
	// Mac address
	MacAddress string `json:"macAddress"`
}
