/*
 * VMware Fusion REST API
 *
 * vmrest 1.3.1 build-24585314
 *
 * API version: 1.3.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type Vmid struct {
	// ID of the VM
	Id string `json:"id"`
	// Path of the VM
	Path string `json:"path"`
}
