/*
 * VMware Fusion REST API
 *
 * vmrest 1.3.1 build-24585314
 *
 * API version: 1.3.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package vmrest

type VmConnectedDevice struct {
	Index int32 `json:"index,omitempty"`
	StartConnected string `json:"startConnected,omitempty"`
	ConnectionStatus int32 `json:"connectionStatus,omitempty"`
	DevicePath string `json:"devicePath,omitempty"`
}
